# Generated by Django 4.2.4 on 2023-08-17 04:06

from django.db import migrations, models
import django.db.models.deletion
import my_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('thumbPoster', models.ImageField(default='', upload_to=my_app.models.get_product_image_upload_path)),
                ('projectPreview', models.ImageField(blank=True, null=True, upload_to=my_app.models.get_product_image_upload_path)),
                ('project_type', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('tools', models.CharField(max_length=255)),
                ('websiteName', models.CharField(max_length=255)),
                ('websiteLink', models.CharField(max_length=255)),
                ('desciption', models.TextField()),
                ('category', models.ManyToManyField(blank=True, related_name='projects_categories', to='my_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=my_app.models.get_product_image_upload_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='my_app.project')),
            ],
        ),
    ]
