# Generated by Django 4.2.4 on 2023-08-17 04:23

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectPreview',
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectPreviewVideo',
            field=models.FileField(blank=True, default='', null=True, upload_to=my_app.models.get_product_image_upload_path),
        ),
    ]
