# Generated by Django 4.2.4 on 2023-08-17 06:42

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_project_projectpreview_project_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=my_app.models.get_product_gallery_upload_path),
        ),
    ]
