# Generated by Django 4.2.4 on 2023-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_aboutme_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='my_skills',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gitRepoLink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gitRepoName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
